/**
 *
 *  Copyright (C) 2020  Raul Casanova Marques
 *
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#ifndef __RKVAC_PROTOCOL_CONTROLLER_VERIFIER_H_
#define __RKVAC_PROTOCOL_CONTROLLER_VERIFIER_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stddef.h>
#include <string.h>

#include <time.h>

#include <mcl/bn_c256.h>
#include <openssl/sha.h>
#include <openssl/rand.h>

#include "config/config.h"

#include "models/issuer.h"
#include "models/revocation-authority.h"
#include "models/user.h"
#include "system.h"

#include "helpers/hash_helper.h"
#include "helpers/mcl_helper.h"

/**
 * Generates a nonce and an epoch to be used in the proof of knowledge.
 *
 * @param nonce the nonce to be generated
 * @param nonce_length the length of the nonce
 * @param epoch the epoch to be generated
 * @param epoch_length the length of the epoch
 * @return 0 if success else -1
 */
extern int ve_generate_nonce_epoch(void *nonce, size_t nonce_length, void *epoch, size_t epoch_length);

/**
 * Verifies the proof of knowledge of the user attributes.
 *
 * @param sys_parameters the system parameters
 * @param ra_parameters the revocation authority parameters
 * @param ra_public_key the revocation authority public key
 * @param ie_keys the issuer keys
 * @param nonce the nonce generated by the verifier
 * @param nonce_length the length of the nonce
 * @param epoch the epoch generated by the verifier
 * @param epoch_length the length of the epoch
 * @param attributes the attributes disclosed by the user
 * @param ue_credential the credential struct computed by the user
 * @param ue_pi the pi struct computed by the user
 * @return 0 if success else -1
 */
extern int ve_verify_proof_of_knowledge(system_par_t sys_parameters, revocation_authority_par_t ra_parameters, revocation_authority_public_key_t ra_public_key,
                                        issuer_keys_t ie_keys, const void *nonce, size_t nonce_length, const void *epoch, size_t epoch_length,
                                        user_attributes_t attributes, user_credential_t ue_credential, user_pi_t ue_pi);

#ifdef __cplusplus
}
#endif

#endif /* __RKVAC_PROTOCOL_CONTROLLER_VERIFIER_H_ */
